# Generated by Django 5.2.14 on 2026-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazen', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
